# WIZnet-PICO-LWIP-C_BUILD_DEFINE: WIZnet-PICO-LWIP-C_SDK_VERSION_MAJOR, SDK major version number
set(WIZnet-PICO-LWIP-C_SDK_VERSION_MAJOR 2)
# WIZnet-PICO-LWIP-C_BUILD_DEFINE: WIZnet-PICO-LWIP-C_SDK_VERSION_MINOR, SDK minor version number
set(WIZnet-PICO-LWIP-C_SDK_VERSION_MINOR 0)
# WIZnet-PICO-LWIP-C_BUILD_DEFINE: WIZnet-PICO-LWIP-C_SDK_VERSION_REVISION, SDK version revision
set(WIZnet-PICO-LWIP-C_SDK_VERSION_REVISION 0)
# WIZnet-PICO-LWIP-C_BUILD_DEFINE: WIZnet-PICO-LWIP-C_SDK_VERSION_STRING, SDK version
set(WIZnet-PICO-LWIP-C_SDK_VERSION_STRING "${WIZnet-PICO-LWIP-C_SDK_VERSION_MAJOR}.${WIZnet-PICO-LWIP-C_SDK_VERSION_MINOR}.${WIZnet-PICO-LWIP-C_SDK_VERSION_REVISION}")

message(STATUS "WIZnet-PICO-LWIP-C SDK version is ${WIZnet-PICO-LWIP-C_SDK_VERSION_STRING}")
